version: "3"
services:
  jarvis:
    restart: always
    container_name: jarvis
    image: tonghs/jarvis:latest
    environment:
      - BOT_TOKEN=<BOT_TOKEN>
      - CHAT_ID=<CHAT_ID>
      - GOOGLE_DRIVE_DATA_DIR=<GOOGLE_DRIVE_DATA_DIR>
      - SENTRY_DSN=<SENTRY_DSN>
