version: "3"
services:
  jarvis:
    restart: always
    container_name: jarvis
    image: tonghs/jarvis:latest
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=<BOT_TOKEN>
      - CHAT_ID=<CHAT_ID>
      - SENTRY_DSN=<SENTRY_DSN>
